# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: cards-deployment
deploymentLabel: cards

replicaCount: 2

image:
  repository: rafik790/bank-cards
  tag: latest

containerPort: 8091

service:
  type: LoadBalancer
  port: 8091
  targetPort: 8091

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: true